### ISSUE TITLE
 build The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### ISSUE THREAD

**Issue by Mieekaserra** [just-the-docs/just-the-docs-template#8]
Picture says 1000 words

![image](https://user-images.githubusercontent.com/26418143/205769597-c2497a78-9a84-4f32-8eb1-4cd29bed47bc.png)

Your Actions tab on this repository have the same Warnings.

**Comment by mattxwang** [comment]
Thanks for submitting this issue @Mieekaserra; one of our actions dependencies provided by GitHub used the deprecated command. I've updated the dependency in #10, and the problem should be resolved; see [this build](https://github.com/just-the-docs/just-the-docs-template/actions/runs/3688407863/jobs/6243172037).

Appreciate your patience!

**Comment by Mieekaserra** [comment]
Hi Matt,

you are still getting one of these on the Ruby line
